server:
  port: 8090
file:
  upload.path: /root/upload/
  download.path: /root/upload/
#  upload.path: C:\chenli\IDEA\Idea_WorkSpace\filedemo\upload\
#  download.path: C:\chenli\IDEA\Idea_WorkSpace\filedemo\upload\
iot-ftp:
  host: 47.107.80.174
  port: 22
  username: root
  password: Cl314159