server:
  port: 8090
file.path:
  target: /opt/upload/
  package: /opt/package/
#  proxy: /opt/download/
#  target: C:\chenli\IDEA\Idea_WorkSpace\filedemo\upload\
  proxy: C:\chenli\IDEA\Idea_WorkSpace\filedemo\download\
ftp:
  host: 145.170.23.230
  port: 22
  username: root
  password: 123456
#  host: 47.107.80.174
#  port: 22
#  username: root
#  password: Cl314159
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB