server:
  port: 8090
file:
  compress.suffix: zip
  path:
    nfs: /opt/upload/
    package: /opt/package/
#  nfs: /opt/download/
#  download: C:\CHENLI\work\idea_workspace\filedemo\upload\
    download: C:\CHENLI\work\idea_workspace\filedemo\download\
ftp:
  host: 145.170.23.230
  port: 22
  username: root
  password: 123456

#上传文件大小设置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB